export class PQCWorkOrder {
  public id?: string;
  public bomVersion?: string;
  public duyetNhapKho?: string;
  public ganLK?: string;
  public inKem?: string;
  public kiemtraNvlResult?: string;
  public kiemTraNvl?: string;
  public kiemTraLapLan?: string;
  public kimLoai?: string;
  public KTChiTietNhapKho?: string;
  public KTLoiSuaLai?: string;
  public KTQuangDien?: string;
  public KTQuangDienBTP?: string;
  public KTQuaTrinhSX?: string;
  public loHan?: string;
  public mauDanhGiaCLSP?: string;
  public nhua?: string;
  public planingWorkOrderCode?: string;
  public planingWorkOrderId?: string;
  public productionCode?: string;
  public productionName?: string;
  public profileId?: string;
  public purchaseOrderCode?: string;
  public rutNghiem?: string;
  public lotNumber?: string;
  public rutnghiemNvlResult?: string;
  public son?: string;
  public workOrderId?: string;
  public createdBy?: string;
  public status?: string;
  public statusSuccess?: string;

  public strStatus?: string;
  public total?: string;
  public totalSap?: string;

  public quantityPlan?: string;
  public createdAt?: string;
  public updatedAt?: string;
  public sapWo?:string;
  public lot?:string;
  public quatity?:string;
  public quatityStore?:string;
  public totalError?:string;
  public conclude?:string;
  public statusApproveSap?:string;
  public storeId?:number;
  public dateApproveSap?:string;
  public quantityStoreSap?:string;
  public groupName?:string;
  public branchName?:string;
}
